apiVersion: v1
kind: Service
metadata:
  name: supplier-service
  namespace: inventory-system
  labels:
    app: supplier-service
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3006
    protocol: TCP
    name: http
  selector:
    app: supplier-service
